DROP TABLE IF EXISTS `t_dict`;
CREATE TABLE `t_dict`
(
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `word` VARCHAR(50) NOT NULL COMMENT '词语',
    `freq` INT(11) NOT NULL DEFAULT 1 COMMENT '词频',
    `category` TINYINT(4) NOT NULL DEFAULT 0 COMMENT '类别',
    `deleted` TINYINT(4) NOT NULL DEFAULT 0 COMMENT '是否删除',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `t_corpus`;
CREATE TABLE `t_corpus`
(
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `sentence` VARCHAR(500) DEFAULT NULL COMMENT '待分词文本',
    `status` TINYINT(4) NOT NULL DEFAULT 0 COMMENT '处理状态',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;